consensus/ethash: use block.NumberU64 instead of header
This actually (miraculously?) fixes the
seed hash error that I was just debugging.

Now we get a new error:

/home/ia/go1.19.2.linux-amd64/bin/go tool test2json -t /tmp/GoLand/___TestRemoteNotify_in_github_com_ledgerwatch_erigon_consensus_ethash.test -test.v -test.paniconexit0 -test.run ^\QTestRemoteNotify\E$
=== RUN   TestRemoteNotify
[WARN] [01-16|11:18:26.529] One ethash cache must always be in memory requested=0
    sealer_test.go:69: work packet hash mismatch: have , want 0xca2ff06caae7c94dc968be7d76d0fbf60dd2e1989ee9bf0d5931e48564d5143b
--- FAIL: TestRemoteNotify (0.00s)

Date: 2023-01-16 11:19:23-08:00
Signed-off-by: meows <b5c6@protonmail.com>